// <auto-generated />
// Generated by tools\gen-resources.ps1 - do not edit by hand.
using System.Globalization;

namespace StudentHousing.Resources
{
    public partial class SharedResource
    {
        public static string CompareAttribute_ValidationError =>
            ResourceManager.GetString("CompareAttribute_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string EmailAddressAttribute_ValidationError =>
            ResourceManager.GetString("EmailAddressAttribute_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string PasswordMismatch_ValidationError =>
            ResourceManager.GetString("PasswordMismatch_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string PhoneAttribute_ValidationError =>
            ResourceManager.GetString("PhoneAttribute_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string RangeAttribute_ValidationError =>
            ResourceManager.GetString("RangeAttribute_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string RequiredAttribute_ValidationError =>
            ResourceManager.GetString("RequiredAttribute_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string StringLengthAttribute_ValidationError =>
            ResourceManager.GetString("StringLengthAttribute_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

        public static string TermsRequired_ValidationError =>
            ResourceManager.GetString("TermsRequired_ValidationError", CultureInfo.CurrentUICulture) ?? string.Empty;

    }
}
