param(
    [string]$InputFile = "Resources\strings.tsv",
    [string]$OutDir = "Resources"
)

# Reads a TSV with columns: target<TAB>key<TAB>en<TAB>ar
# and generates <OutDir>\<target>.resx (English/neutral) and <OutDir>\<target>.ar-EG.resx (Arabic).

$ErrorActionPreference = "Stop"
# Skip blank/comment lines; Import-Csv treats the first data line as headers.
$rows = Get-Content -Path $InputFile -Encoding UTF8 |
    Where-Object { $_ -and -not $_.TrimStart().StartsWith('#') } |
    ConvertFrom-Csv -Delimiter "`t"

$cultures = @{ "en" = $null; "ar" = ".ar-EG" }
$byTarget = @{}
foreach ($r in $rows) {
    $t = $r.target
    if (-not $byTarget.ContainsKey($t)) { $byTarget[$t] = @() }
    $byTarget[$t] += $r
}

function New-Resx([string]$name, [object[]]$entries) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
    [void]$sb.AppendLine('<root>')
    [void]$sb.AppendLine('  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>')
    [void]$sb.AppendLine('  <resheader name="version"><value>2.0</value></resheader>')
    [void]$sb.AppendLine('  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
    [void]$sb.AppendLine('  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
    foreach ($e in $entries) {
        $key = [System.Security.SecurityElement]::Escape($e.key)
        $val = [System.Security.SecurityElement]::Escape($e.value)
        [void]$sb.AppendLine("  <data name=`"$key`" xml:space=`"preserve`">")
        [void]$sb.AppendLine("    <value>$val</value>")
        [void]$sb.AppendLine("  </data>")
    }
    [void]$sb.AppendLine('</root>')
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText((Join-Path $OutDir $name), $sb.ToString(), $utf8NoBom)
    Write-Host "Generated $name ($($entries.Count) entries)"
}

foreach ($target in $byTarget.Keys) {
    $dir = Join-Path $OutDir (Split-Path $target -Parent)
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
    $rowsFor = $byTarget[$target]
    $enEntries = $rowsFor | ForEach-Object { @{ key = $_.key; value = $_.en } } | Where-Object { -not [string]::IsNullOrEmpty($_.value) }
    $arEntries = $rowsFor | ForEach-Object { @{ key = $_.key; value = $_.ar } } | Where-Object { -not [string]::IsNullOrEmpty($_.value) }
    New-Resx "$target.resx" $enEntries
    New-Resx "$target.ar-EG.resx" $arEntries
}

# Emit SharedResource.Validation.cs: a static property per "<name>_ValidationError"
# key so DataAnnotations attributes can reference them via ErrorMessageResourceName
# (System.ComponentModel.DataAnnotations requires an actual static property on the
# resource type - the plain ResourceManager fallback no longer exists in .NET 10).
$sharedRows = $byTarget["SharedResource"]
$validationKeys = $sharedRows |
    ForEach-Object { $_.key } |
    Where-Object { $_ -match '^[A-Za-z_][A-Za-z0-9_]*_ValidationError$' } |
    Sort-Object -Unique

if ($validationKeys) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// <auto-generated />")
    [void]$sb.AppendLine("// Generated by tools\gen-resources.ps1 - do not edit by hand.")
    [void]$sb.AppendLine("using System.Globalization;")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("namespace StudentHousing.Resources")
    [void]$sb.AppendLine("{")
    [void]$sb.AppendLine("    public partial class SharedResource")
    [void]$sb.AppendLine("    {")
    foreach ($k in $validationKeys) {
        [void]$sb.AppendLine("        public static string $k =>")
        [void]$sb.AppendLine("            ResourceManager.GetString(`"$k`", CultureInfo.CurrentUICulture) ?? string.Empty;")
        [void]$sb.AppendLine("")
    }
    [void]$sb.AppendLine("    }")
    [void]$sb.AppendLine("}")
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText((Join-Path $OutDir "SharedResource.Validation.cs"), $sb.ToString(), $utf8NoBom)
    Write-Host "Generated SharedResource.Validation.cs ($($validationKeys.Count) accessors)"
}
