using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StudentHousing.Models
{
    public class Property
    {
        public int Id { get; set; }

        /// <summary>Human-readable public ID (e.g. APT-10482). Generated by the system, unique.</summary>
        [StringLength(20)]
        public string? PublicId { get; set; }

        [Required]
        public string OwnerId { get; set; } = string.Empty;

        [Required, StringLength(150)]
        public string Title { get; set; } = string.Empty;

        [Required, StringLength(2000)]
        public string Description { get; set; } = string.Empty;

        public PropertyType PropertyType { get; set; } = PropertyType.Apartment;

        [Required, StringLength(200)]
        public string Address { get; set; } = string.Empty;

        [Required, StringLength(100)]
        public string City { get; set; } = string.Empty;

        [Required, StringLength(50)]
        public string State { get; set; } = string.Empty;

        [StringLength(100)]
        public string? District { get; set; }

        [StringLength(20)]
        public string? ZipCode { get; set; }

        [StringLength(150)]
        public string? University { get; set; }

        public double? Latitude { get; set; }
        public double? Longitude { get; set; }

        /// <summary>Calculated distance from the nearest university (km), if coordinates exist.</summary>
        public double? DistanceFromUniversityKm { get; set; }

        /// <summary>True when a significant change since approval awaits another admin review.</summary>
        public bool IsModifiedSinceApproval { get; set; }

        [Range(0, int.MaxValue)]
        public int Deposit { get; set; }

        public int Bedrooms { get; set; }
        public int Bathrooms { get; set; }
        public bool IsFurnished { get; set; }
        public bool PetAllowed { get; set; }

        public DateTime? AvailableFrom { get; set; }

        public ApprovalStatus ApprovalStatus { get; set; } = ApprovalStatus.Pending;

        /// <summary>Rejection / moderation note from an admin.</summary>
        [StringLength(500)]
        public string? AdminNote { get; set; }

        public bool IsActive { get; set; } = true;
        public bool IsFeatured { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        public OwnerProfile Owner { get; set; } = null!;
        public ICollection<PropertyImage> Images { get; set; } = new List<PropertyImage>();
        public ICollection<Room> Rooms { get; set; } = new List<Room>();
        public ICollection<PropertyReview> Reviews { get; set; } = new List<PropertyReview>();
        public ICollection<Amenity> Amenities { get; set; } = new List<Amenity>();

        /// <summary>Cheapest active room rent, used for listing cards.</summary>
        [NotMapped]
        public int MinRoomRent =>
            Rooms.Count == 0 ? 0 : Rooms.Where(r => r.IsAvailable).Select(r => r.RentPerMonth).DefaultIfEmpty(0).Min();
    }
}
